### ISSUE TITLE
epubcheck-ruby silently exits if java is not on PATH

### ISSUE THREAD

**Issue by slonopotamus** [takahashim/epubcheck-ruby#18]
Downstream issue: https://github.com/asciidoctor/asciidoctor-epub3/issues/404

It would be much more friendly if there was some kind of error message on stderr.

**Comment by slonopotamus** [comment]
Proposed solutions:
1. Simplest one: use `exec` instead of `system` in `Epubcheck::Ruby::CLI#execute`. Although this has a small chance of breaking someone's workflow it they are calling this method directly from Ruby code.
2. Check `system` return value. If it is `nil`, print error message. But I'm not sure we can get error description from anywhere: is `java` missing? Or maybe it doesn't have executable bit set?
3. Suggest your own

**Comment by takahashim** [comment]
Thank you for your feedback!  I use 2, which is a simple solution.
